version: 1
formatters:
  simple:
    format: '%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)'
    datefmt: '%x %I:%M:%S %p'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: "${hydra.run.dir}/${hydra.job.name}.log"
  sys_err:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: "${hydra.run.dir}/system.log"
loggers:
  myLogger:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [sys_err]
disable_existing_loggers: false
